services:
  # Application service for production
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acquisitions-app-prod
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL} # Neon Cloud connection string
      - PORT=${PORT:-3000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - ARCJET_KEY=${ARCJET_KEY}
    env_file:
      - .env.production
    networks:
      - acquisitions-network
    volumes:
      - ./logs:/app/logs
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  acquisitions-network:
    driver: bridge
